# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181104_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['name']},
        ),
    ]
